apiPackage: org.lankheet.domiot.api
invokerPackage: org.lankheet.domiot.invoker
modelPackage: org.lankheet.domiot.model
configPackage: org.lankheet.domiot.config
dateLibrary: java8-localdatetime
interfaceOnly: true
serializableModel: true
modelTests: false
useTags: true
